jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Java for test
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Setup Java for mvn
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      if: ${{ matrix.java >= 17 }}
      name: Maven Test With Spring 6.x
      run: mvn --batch-mode test -Dsurefire.jdk-toolchain-version=${{ matrix.java
        }}
    - continue-on-error: true
      if: ${{ matrix.java < 17 }}
      name: Maven Test Without Spring 6.x
      run: mvn --batch-mode test -Dsurefire.jdk-toolchain-version=${{ matrix.java
        }} -Dskip.spring.v6x.test=true
    - continue-on-error: true
      name: Build with Maven
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DminimumPriority=1
    - continue-on-error: true
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
name: Sentinel CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
