jobs:
  document-lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      run: npm install -g markdownlint-cli
    - continue-on-error: true
      name: use markdownlint-cli to lint markdown file
      run: 'find ./ -name "*.md" | grep -v vendor | grep -v commandline | grep -v
        .github | grep -v swagger | grep -v api | \

        xargs markdownlint --disable MD010 MD013 MD024 MD029 MD033 MD036 --

        '
name: document-lint
on:
  repository_dispatch:
    types: trigger-ga___document-lint.yml
